apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 8081
    targetPort: 8081
  selector:
    app: vote
